//! Delta-t / time variance tests (issue 3.2).
//!
//! - **Property/error** (synthetic laps): the behavioural contract — starts at
//!   zero, ends at the lap-time difference, identical laps → zero, sign
//!   convention (slower ⇒ positive), and the two typed error paths. Deterministic
//!   and fixture-free.
//! - **Golden** (`test_delta_matches_golden`): reproduce the committed
//!   `delta_t` of a reference lap vs the fastest lap over the real
//!   `aim_official_test.xrk`. The `.xrk` is git-ignored (fetched by
//!   `make fixtures`); the test skips cleanly when it is absent.
//!
//! The golden is regenerated by the `#[ignore]`d `generate_delta_golden` below.

use std::path::PathBuf;

use crate::support::fixtures::{fixture_path, load_golden, DeltaGolden, LapsGolden};
use racestudio_analysis::{delta_t, segment_laps, AnalysisError, Lap, LapChannel};
use racestudio_decode::{decode_session, Session};

const SAMPLE: &str = "aim_official_test.xrk";

fn xrk_or_skip(name: &str) -> Option<PathBuf> {
    let path = fixture_path(name);
    match std::fs::read(&path) {
        Ok(bytes) if bytes.starts_with(b"<h") => Some(path),
        _ => {
            eprintln!(
                "skipping: {} is not a real .xrk sample — run `make fixtures` to fetch it",
                path.display()
            );
            None
        }
    }
}

fn decoded_session() -> Option<Session> {
    let path = xrk_or_skip(SAMPLE)?;
    Some(decode_session(&path).expect("decode session"))
}

/// A lap carrying only a `GPS Speed` channel (all delta-t needs) whose absolute
/// sample times are as given; `[start, end)` spans them.
fn speed_lap(number: u32, start_ms: f64, speed: &[(f64, f64)]) -> Lap {
    let end_ms = speed.iter().map(|&(t, _)| t).fold(start_ms, f64::max) + 1.0;
    Lap::new(
        number,
        start_ms,
        end_ms,
        vec![LapChannel::new("GPS Speed", speed.to_vec())],
    )
}

/// Last re-based sample time (seconds) — the time span the lap's samples cover.
fn covered_time_s(speed: &[(f64, f64)], start_ms: f64) -> f64 {
    (speed.last().map(|&(t, _)| t).unwrap_or(start_ms) - start_ms) / 1000.0
}

/// Linear interpolation of a `(distance, dt)` series at `distance`.
fn dt_at(series: &[(f64, f64)], distance: f64) -> f64 {
    if distance <= series[0].0 {
        return series[0].1;
    }
    for pair in series.windows(2) {
        let (d0, v0) = pair[0];
        let (d1, v1) = pair[1];
        if distance <= d1 {
            return v0 + (v1 - v0) * (distance - d0) / (d1 - d0);
        }
    }
    series[series.len() - 1].1
}

// --------------------------------------------------------------------------- //
// Property tests (synthetic)
// --------------------------------------------------------------------------- //

#[test]
fn test_delta_t_starts_at_zero() {
    let reference = speed_lap(0, 0.0, &[(0.0, 10.0), (1000.0, 10.0), (2000.0, 10.0)]);
    let comparison = speed_lap(1, 0.0, &[(0.0, 8.0), (1000.0, 12.0), (2000.0, 8.0)]);

    let series = delta_t(&reference, &comparison).expect("delta_t");

    assert!(!series.is_empty());
    assert_eq!(series[0].0, 0.0, "series starts at distance 0");
    assert_eq!(series[0].1, 0.0, "delta-t at distance 0 is exactly 0");
}

#[test]
fn test_delta_t_final_equals_laptime_difference() {
    // Reference covers 100 m in 10 s; comparison covers the same 100 m in 20 s.
    let reference_speed = [(0.0, 10.0), (10000.0, 10.0)];
    let comparison_speed = [(0.0, 0.0), (20000.0, 10.0)];
    let reference = speed_lap(0, 0.0, &reference_speed);
    let comparison = speed_lap(1, 0.0, &comparison_speed);

    let series = delta_t(&reference, &comparison).expect("delta_t");

    let expected = covered_time_s(&comparison_speed, 0.0) - covered_time_s(&reference_speed, 0.0);
    let final_dt = series.last().expect("non-empty").1;
    assert!(
        (final_dt - expected).abs() < 1e-6,
        "final delta-t {final_dt} should equal lap-time difference {expected}"
    );
}

#[test]
fn test_identical_laps_produce_zero_series() {
    let lap = speed_lap(
        0,
        0.0,
        &[(0.0, 10.0), (1000.0, 20.0), (2000.0, 15.0), (3000.0, 25.0)],
    );

    let series = delta_t(&lap, &lap).expect("delta_t");

    assert!(!series.is_empty());
    for (distance, dt) in &series {
        assert!(
            dt.abs() < 1e-9,
            "dt at {distance} must be 0 for identical laps"
        );
    }
}

#[test]
fn test_sign_convention_slower_is_positive() {
    // Comparison is slower everywhere (lower speed → later at each distance), so
    // delta-t must be positive.
    let reference = speed_lap(0, 0.0, &[(0.0, 20.0), (5000.0, 20.0), (10000.0, 20.0)]);
    let comparison = speed_lap(1, 0.0, &[(0.0, 10.0), (5000.0, 10.0), (20000.0, 10.0)]);

    let series = delta_t(&reference, &comparison).expect("delta_t");

    let final_dt = series.last().expect("non-empty").1;
    assert!(
        final_dt > 0.0,
        "slower comparison ⇒ positive delta-t, got {final_dt}"
    );
    assert!(
        series.iter().all(|&(_, dt)| dt >= -1e-9),
        "a uniformly slower lap never gains time"
    );
}

#[test]
fn test_empty_lap_returns_error() {
    // A lap with no GPS Speed channel cannot yield a distance axis → EmptyLap.
    let channelless = Lap::new(0, 0.0, 10.0, vec![LapChannel::new("RPM", vec![(0.0, 1.0)])]);
    let valid = speed_lap(1, 0.0, &[(0.0, 10.0), (1000.0, 10.0)]);
    assert_eq!(
        delta_t(&channelless, &valid).expect_err("channel-less reference"),
        AnalysisError::EmptyLap
    );

    // A present-but-empty speed channel is likewise empty.
    let empty = Lap::new(0, 0.0, 10.0, vec![LapChannel::new("GPS Speed", vec![])]);
    assert_eq!(
        delta_t(&empty, &valid).expect_err("empty speed channel"),
        AnalysisError::EmptyLap
    );
}

#[test]
fn test_non_monotonic_distance_returns_error() {
    // A negative speed excursion makes the faithful distance integral dip, so the
    // distance axis is not monotonic → DistanceNotMonotonic (not a panic).
    let reference = speed_lap(0, 0.0, &[(0.0, 10.0), (1000.0, -50.0), (2000.0, 10.0)]);
    let comparison = speed_lap(1, 0.0, &[(0.0, 10.0), (1000.0, 10.0)]);
    assert_eq!(
        delta_t(&reference, &comparison).expect_err("non-monotonic distance"),
        AnalysisError::DistanceNotMonotonic
    );
}

#[test]
fn test_zero_distance_reference_no_panic() {
    // A stationary reference lap (speed 0 → total distance 0) is degenerate but
    // valid (its distance axis is non-empty and non-decreasing); delta-t must not
    // divide by the zero span — it collapses to the start line without panicking.
    let stationary = speed_lap(0, 0.0, &[(0.0, 0.0), (1000.0, 0.0)]);
    let comparison = speed_lap(1, 0.0, &[(0.0, 10.0), (1000.0, 10.0)]);

    let series = delta_t(&stationary, &comparison).expect("delta_t");

    assert_eq!(series.len(), 2);
    assert!(series.iter().all(|&(_, dt)| dt.abs() < 1e-9));
}

// --------------------------------------------------------------------------- //
// Golden
// --------------------------------------------------------------------------- //

#[test]
fn test_delta_matches_golden() {
    let Some(session) = decoded_session() else {
        return;
    };
    let laps = segment_laps(&session);
    let g: DeltaGolden = load_golden("aim_official_test", "delta_t").expect("load delta golden");
    assert_eq!(g.file, SAMPLE);
    let reference = &laps[g.reference_index];
    let comparison = &laps[g.comparison_index];

    let series = delta_t(reference, comparison).expect("delta_t");

    assert!(series[0].1.abs() < 1e-9, "golden series starts at 0");
    for point in &g.points {
        let dt = dt_at(&series, point.distance);
        assert!(
            (dt - point.dt).abs() < 1e-3,
            "delta-t at distance {}: computed {dt} vs golden {}",
            point.distance,
            point.dt
        );
    }
}

#[test]
fn test_delta_final_matches_beacon_laptime_difference() {
    // Independent oracle: the final delta-t must equal the difference of the two
    // laps' libxrk-validated beacon durations (issue 1.5 golden). The ~0.07 s
    // slack is the GPS-sample time span (first fix → last fix) versus the beacon
    // marker duration; both laps carry a similar offset, so it nearly cancels.
    let Some(session) = decoded_session() else {
        return;
    };
    let laps = segment_laps(&session);
    let dg: DeltaGolden = load_golden("aim_official_test", "delta_t").expect("delta golden");
    let lg: LapsGolden = load_golden("aim_official_test", "laps").expect("laps golden");

    let series = delta_t(&laps[dg.reference_index], &laps[dg.comparison_index]).expect("delta_t");

    let final_dt = series.last().expect("non-empty").1;
    let beacon_diff = (lg.laps[dg.comparison_index].duration_ms
        - lg.laps[dg.reference_index].duration_ms) as f64
        / 1000.0;
    assert!(
        (final_dt - beacon_diff).abs() < 0.25,
        "final delta-t {final_dt}s vs beacon lap-time difference {beacon_diff}s"
    );
}

/// Regenerate `fixtures/golden/aim_official_test.delta_t.json` from the decoded
/// fixture. Not part of the normal run; execute with:
/// `cargo test -p racestudio-analysis --test delta_test -- --ignored generate_delta_golden`
#[test]
#[ignore = "regenerates the delta_t golden; run with --ignored"]
fn generate_delta_golden() {
    let session = decoded_session().expect("fixture required to regenerate the golden");
    let laps = segment_laps(&session);
    let reference_index = 1usize; // first flying lap (lap 0 is the out-lap)
    let comparison_index = session.laps().best_lap_index().expect("a fastest lap") as usize;

    let series = delta_t(&laps[reference_index], &laps[comparison_index]).expect("delta_t");

    // Sample ~25 evenly spaced grid points.
    let n = 25.min(series.len());
    let round6 = |x: f64| (x * 1e6).round() / 1e6;
    let points: Vec<serde_json::Value> = (0..n)
        .map(|k| {
            let idx = if n <= 1 {
                0
            } else {
                k * (series.len() - 1) / (n - 1)
            };
            let (distance, dt) = series[idx];
            serde_json::json!({ "distance": round6(distance), "dt": round6(dt) })
        })
        .collect();
    let golden = serde_json::json!({
        "file": SAMPLE,
        "reference_index": reference_index,
        "comparison_index": comparison_index,
        "point_count": points.len(),
        "points": points,
    });

    let path = fixture_path("golden").join("aim_official_test.delta_t.json");
    let mut text = serde_json::to_string_pretty(&golden).expect("serialize golden");
    text.push('\n');
    std::fs::write(&path, text).expect("write golden");
    eprintln!("wrote {}", path.display());
}
