//! Session-wide cumulative-distance tests (issue 8.2).
//!
//! [`cumulative_distance`] integrates a `GPS Speed` series (m/s over ms
//! timecodes) into a monotonically non-decreasing cumulative distance (m) — the
//! axis the FFI distance accessors (`samples_with_distance` / `gps_track`, 8.2)
//! read for distance-mode plots and the track map. Two layers:
//!
//! - **Property** (synthetic speed): the integration contract — empty / single,
//!   constant rate, and the non-negative clamp — deterministic and fixture-free.
//! - **Golden** (`test_distance_matches_golden`): reproduce the committed
//!   cumulative distance for the real fixture (`track`) against the numpy oracle
//!   generated by `scripts/gen_goldens.py`. The linear interpolation onto a
//!   channel timebase that `samples_with_distance` layers on top is itself
//!   golden-tested by the resample golden (3.3). The `.xrk` is git-ignored
//!   (fetched by `make fixtures`); the test skips cleanly when it is absent.

use std::path::PathBuf;

use crate::support::fixtures::{fixture_path, load_golden, DistanceGolden};
use racestudio_analysis::cumulative_distance;
use racestudio_decode::{decode_session, Session};

const SAMPLE: &str = "aim_official_test.xrk";

fn xrk_or_skip(name: &str) -> Option<PathBuf> {
    let path = fixture_path(name);
    match std::fs::read(&path) {
        Ok(bytes) if bytes.starts_with(b"<h") => Some(path),
        _ => {
            eprintln!(
                "skipping: {} is not a real .xrk sample — run `make fixtures` to fetch it",
                path.display()
            );
            None
        }
    }
}

fn decoded_session() -> Option<Session> {
    let path = xrk_or_skip(SAMPLE)?;
    Some(decode_session(&path).expect("decode session"))
}

/// A channel's `(timecode, value)` samples by name — CHS channels first, then
/// GPS channels (which carry `GPS Speed`).
fn channel_samples<'a>(session: &'a Session, name: &str) -> Option<&'a [(f64, f64)]> {
    if let Some(channel) = session.channels().iter().find(|c| c.name() == name) {
        return Some(channel.samples());
    }
    session
        .gps()
        .and_then(|gps| gps.channel(name))
        .map(|channel| channel.samples())
}

// --------------------------------------------------------------------------- //
// Property (synthetic)
// --------------------------------------------------------------------------- //

#[test]
fn test_cumulative_distance_empty_and_single_is_zero_based() {
    // No samples → no axis; a single sample sits at distance 0 (nothing to
    // integrate yet).
    assert!(cumulative_distance(&[]).is_empty());
    assert_eq!(cumulative_distance(&[(0.0, 12.0)]), vec![0.0]);
}

#[test]
fn test_cumulative_distance_constant_rate_integrates_linearly() {
    // 10 m/s held over two 1 s steps → 10 m, then 20 m.
    let speed = [(0.0, 10.0), (1000.0, 10.0), (2000.0, 10.0)];
    assert_eq!(cumulative_distance(&speed), vec![0.0, 10.0, 20.0]);
}

#[test]
fn test_cumulative_distance_clamps_backward_steps() {
    // A negative-speed excursion would make a faithful integral dip; the axis is
    // clamped so it never decreases (each step's area floored at 0), keeping it
    // monotonic — the invariant `to_distance_grid` and distance-mode plots need.
    let speed = [(0.0, 10.0), (1000.0, -50.0), (2000.0, 10.0)];
    let axis = cumulative_distance(&speed);

    assert_eq!(axis, vec![0.0, 0.0, 0.0]);
    assert!(
        axis.windows(2).all(|w| w[1] >= w[0]),
        "axis stays monotonic"
    );
}

// --------------------------------------------------------------------------- //
// Golden
// --------------------------------------------------------------------------- //

/// Absolute distance tolerance (m). The clamped trapezoidal integral uses only
/// timecode differences and the per-sample `GPS Speed`, which the decoder
/// matches to libxrk within the 6-dp GPS-speed golden (~5e-7 m/s); integrated
/// over a session that is well under an hour this leaves the cumulative distance
/// far inside a centimetre. See docs/DECODE_TOLERANCES.md.
const DISTANCE_TOL_M: f64 = 1e-2;

#[test]
fn test_distance_matches_golden() {
    let Some(session) = decoded_session() else {
        return;
    };
    let g: DistanceGolden = load_golden("aim_official_test", "distance").expect("distance golden");
    assert_eq!(g.file, SAMPLE);
    let speed_channel = g.speed_channel.as_deref().expect("fixture has GPS Speed");

    let speed = channel_samples(&session, speed_channel).expect("GPS Speed samples");
    let axis = cumulative_distance(speed);
    assert_eq!(axis.len(), g.fix_count, "fix count matches the oracle");

    // Distances are measured from the reference fix (past the initial GPS gap),
    // which cancels the constant timecode-origin offset between the decoders.
    let ref_dist = axis[g.ref_index];

    // The track axis: cumulative distance at each fix index, relative to the ref.
    assert!(
        (axis.last().copied().unwrap_or(0.0) - ref_dist - g.total_distance_m).abs()
            < DISTANCE_TOL_M,
        "total distance {} vs golden {}",
        axis.last().copied().unwrap_or(0.0) - ref_dist,
        g.total_distance_m
    );
    for point in &g.track {
        assert!(
            (axis[point.i] - ref_dist - point.distance).abs() < DISTANCE_TOL_M,
            "distance at fix {}: computed {} vs golden {}",
            point.i,
            axis[point.i] - ref_dist,
            point.distance
        );
    }
}
